import { biomarkers, compounds } from './data';
import { exportLabsCsv, type LabEntry } from './labs';
import { analyzeStack, hallmarkDisplayNames } from './stack-analysis';
import type { Profile } from '@/context/PlatformContext';
import type { HallmarkNotesMap } from './hallmark-notes';
import type { UserMilestone } from './milestone-engine';

export type ExportFormat = 'json' | 'csv' | 'stack-text' | 'physician-md';

export interface ExportKitPayload {
  stack: string[];
  profile: Profile;
  labs: LabEntry[];
  checklist: string[];
  hallmarkNotes: HallmarkNotesMap;
  milestones?: UserMilestone[];
}

export function buildExportFilename(format: ExportFormat): string {
  const date = new Date().toISOString().slice(0, 10);
  const ext =
    format === 'json' ? 'json' : format === 'csv' ? 'csv' : format === 'physician-md' ? 'md' : 'txt';
  const suffix =
    format === 'physician-md' ? 'physician-summary' : format === 'stack-text' ? 'stack' : 'tnic-export';
  return `tnic-${suffix}-${date}.${ext}`;
}

export function buildJsonExport(payload: ExportKitPayload): string {
  return JSON.stringify(
    {
      ...payload,
      exportedAt: new Date().toISOString(),
      source: 'tnic.help',
      version: 1,
    },
    null,
    2,
  );
}

export function buildStackTextExport(payload: ExportKitPayload): string {
  const analysis = analyzeStack(payload.stack);
  const selected = compounds.filter((c) => payload.stack.includes(c.id));
  const lines: string[] = [
    'TNiC Longevity OS — Stack Summary',
    `Generated: ${new Date().toLocaleString()}`,
    '',
    `Synergy score: ${analysis.score}`,
    `Hallmarks covered: ${analysis.hallmarkCount}/12`,
    `Evidence tier: ${analysis.evidenceTier}`,
    '',
    '── Compounds ──',
  ];

  selected.forEach((c) => {
    lines.push(`• ${c.name} (${c.brand})`);
    lines.push(`  Dose: ${c.dose} · ${c.timing} · Evidence ${c.evidence}`);
    lines.push(`  Pathway: ${c.pathway}`);
    lines.push(`  Hallmarks: ${c.hallmarks.map((h) => hallmarkDisplayNames[h] ?? h).join(', ')}`);
  });

  if (analysis.synergies.length) {
    lines.push('', '── Synergies ──');
    analysis.synergies.forEach((s) => lines.push(`• ${s.label}`));
  }

  if (analysis.cautions.length) {
    lines.push('', '── Cautions ──');
    analysis.cautions.slice(0, 6).forEach((c) => lines.push(`• ${c}`));
  }

  if (payload.profile.scanned) {
    lines.push('', '── Defense profile ──');
    lines.push(`Chronological age: ${payload.profile.age}`);
  }

  lines.push('', 'Educational only — not medical advice. Data exported locally from tnic.help.');
  return lines.join('\n');
}

export function buildPhysicianMarkdown(payload: ExportKitPayload): string {
  const analysis = analyzeStack(payload.stack);
  const selected = compounds.filter((c) => payload.stack.includes(c.id));
  const date = new Date().toISOString().slice(0, 10);

  const lines: string[] = [
    `# Longevity protocol summary (patient-exported)`,
    '',
    `**Date:** ${date}  `,
    `**Source:** [tnic.help](https://tnic.help) — educational platform, not a clinical record`,
    '',
    '> This document was generated by the patient from browser-local data. It is not a prescription or medical recommendation.',
    '',
    '## Active stack',
    '',
    '| Compound | Dose | Timing | Evidence | Pathway |',
    '| --- | --- | --- | --- | --- |',
  ];

  selected.forEach((c) => {
    lines.push(`| ${c.name} | ${c.dose} | ${c.timing} | Tier ${c.evidence} | ${c.pathway} |`);
  });

  lines.push(
    '',
    `**Synergy score (model):** ${analysis.score}  `,
    `**Hallmark coverage:** ${analysis.hallmarkCount}/12`,
    '',
    '## Documented interactions & cautions',
    '',
  );

  if (analysis.interactions.length) {
    analysis.interactions.forEach((i) => {
      lines.push(`- **${i.title}** (${i.type}, ${i.severity}): ${i.detail}`);
    });
  } else {
    lines.push('- No pair-level interactions flagged for current selection.');
  }

  if (analysis.consultIf.length) {
    lines.push('', '### Consult physician if');
    analysis.consultIf.slice(0, 8).forEach((c) => lines.push(`- ${c}`));
  }

  if (payload.labs.length) {
    lines.push('', '## Logged biomarkers', '', '| Date | Marker | Value |', '| --- | --- | --- |');
    payload.labs
      .slice()
      .sort((a, b) => b.date.localeCompare(a.date))
      .slice(0, 20)
      .forEach((e) => {
        const b = biomarkers.find((x) => x.id === e.markerId);
        const label = b ? `${b.name} (${b.unit})` : e.markerId;
        lines.push(`| ${e.date} | ${label} | ${e.value} |`);
      });
  }

  if (payload.milestones?.length) {
    lines.push('', '## Patient-noted milestones', '');
    payload.milestones.slice(-5).forEach((m) => {
      lines.push(`- **${m.date}** — ${m.title}: ${m.desc}`);
    });
  }

  lines.push(
    '',
    '---',
    '',
    '*Disclaimer: TNiC provides educational longevity science. Discuss any supplement changes with a qualified clinician.*',
  );

  return lines.join('\n');
}

export function buildExportContent(format: ExportFormat, payload: ExportKitPayload): string {
  switch (format) {
    case 'json':
      return buildJsonExport(payload);
    case 'csv':
      return exportLabsCsv(payload.labs);
    case 'stack-text':
      return buildStackTextExport(payload);
    case 'physician-md':
      return buildPhysicianMarkdown(payload);
  }
}

export function downloadExport(format: ExportFormat, payload: ExportKitPayload): void {
  const content = buildExportContent(format, payload);
  const mime =
    format === 'json'
      ? 'application/json'
      : format === 'csv'
        ? 'text/csv'
        : 'text/plain';
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = buildExportFilename(format);
  a.click();
  URL.revokeObjectURL(url);
}