import type { EvidenceTier } from './types';

export type LibraryModuleCategory = 'compounds' | 'synergies' | 'lifestyle' | 'guides';

export interface LibraryModule {
  slug: string;
  category: LibraryModuleCategory;
  title: string;
  tagline: string;
  summary: string;
  evidenceTier: EvidenceTier;
  relatedHallmarkIds: string[];
  compoundId?: string;
  synergyCompoundIds?: string[];
  relatedSynergySlugs?: string[];
  requiresDisclaimer?: boolean;
  outline: string[];
  mdxSlug: string;
}

export const libraryCategoryMeta: Record<
  LibraryModuleCategory,
  { label: string; description: string; hubOrder: number }
> = {
  compounds: {
    label: 'Compound Deep-Dives',
    description:
      'Mechanism, evidence tiers, dosing protocols, monitoring checklists, and personal results templates for each intervention.',
    hubOrder: 1,
  },
  synergies: {
    label: 'Synergy Guides',
    description:
      'Multi-compound combinations with mechanistic rationale, trial data, timing choreography, and contraindication notes.',
    hubOrder: 2,
  },
  lifestyle: {
    label: 'Lifestyle Pillars',
    description:
      'Exercise, sleep, nutrition, and stress — mapped to hallmarks with actionable protocols and biomarker tie-ins.',
    hubOrder: 3,
  },
  guides: {
    label: 'Testing & Monitoring',
    description:
      'What to test, when to retest, how to interpret trends, and how lab data connects to your stack.',
    hubOrder: 4,
  },
};

export const libraryModules: LibraryModule[] = [
  // ── Compounds ──────────────────────────────────────────────────────────────
  {
    slug: 'glynac',
    category: 'compounds',
    title: 'GlyNAC (Glycine + NAC)',
    tagline: 'Flagship glutathione restoration — human RCT backbone',
    summary:
      'Dual-precursor strategy rebuilding the glutathione triad (GSH, cysteine, glycine). Tier A human data for oxidative stress, mitochondrial function, and inflammaging markers.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'proteostasis', 'inflammation', 'genomic'],
    compoundId: 'glynac',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & hallmark mapping',
      'Mechanism: GSH synthesis bottleneck',
      'Evidence summary (Kumar et al. RCTs)',
      'Dosing protocol (AM/PM, cycling)',
      'Monitoring: GSH, 8-OHdG, hs-CRP',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'glynac',
  },
  {
    slug: 'nmn',
    category: 'compounds',
    title: 'NMN (Nicotinamide Mononucleotide)',
    tagline: 'NAD+ precursor — sirtuin and PARP fuel',
    summary:
      'Direct NAD+ precursor bypassing NAMPT rate-limiting step. Restores NAD+ pools that decline ~50% between ages 40–60, activating SIRT1/3, DNA repair, and mitophagy.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    compoundId: 'nmn',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1', 'nad-mito-stack'],
    outline: [
      'Overview & NAD+ decline curve',
      'Mechanism: NMN → NAD+ → SIRT/PARP axis',
      'Evidence summary (human PK + biomarkers)',
      'Dosing protocol & resveratrol pairing',
      'Monitoring: NAD+ index, metabolic markers',
      'Safety & methyl donor considerations',
      'Personal results template',
    ],
    mdxSlug: 'nmn',
  },
  {
    slug: 'nr',
    category: 'compounds',
    title: 'NR (Nicotinamide Riboside)',
    tagline: 'NAD+ precursor alternative — human RCT data, manual stack substitution',
    summary:
      'Legitimate NAD+ precursor with human trial footprint. TNiC defaults to NMN for stack integration; this module covers when NR is the right choice, dosing, buyer verification, and compare-table evidence.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'genomic', 'epigenetic', 'senescence', 'nutrient'],
    relatedSynergySlugs: ['nad-mito-stack', 'nmn-resveratrol-sirt1'],
    outline: [
      'Overview & NR → NMN → NAD+ pathway',
      'When to choose NR vs NMN',
      'Evidence summary (Martens, Trammell)',
      'Dosing & NR-Cl form requirements',
      'TNiC stack substitution guide',
      'Buyer guide & red flags',
      'Personal results template',
    ],
    mdxSlug: 'nr',
  },
  {
    slug: 'rapamycin',
    category: 'compounds',
    title: 'Rapamycin (Sirolimus)',
    tagline: 'mTORC1 inhibition — strongest preclinical lifespan drug',
    summary:
      'Educational deep-dive on the most replicated lifespan-extending pharmacological intervention. Prescription-only; immunosuppressive risks require physician oversight.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'nutrient', 'senescence', 'mito'],
    requiresDisclaimer: true,
    relatedSynergySlugs: [],
    outline: [
      'Overview & mTOR/AMPK balance',
      'Mechanism: mTORC1 → autophagy induction',
      'Evidence: mouse, dog, PEARL trial',
      'Decision tree & physician checklist',
      'Dosing paradigms (pulse vs continuous)',
      'Monitoring: CBC, lipids, infection vigilance',
      'Buyer/sourcing guide (Rx only)',
      'Personal results template (physician-supervised)',
    ],
    mdxSlug: 'rapamycin',
  },
  {
    slug: 'tudca',
    category: 'compounds',
    title: 'TUDCA (Tauroursodeoxycholic Acid)',
    tagline: 'ER stress chaperone — proteostasis & mitochondrial support',
    summary:
      'Bile acid derivative stabilizing protein folding, reducing ER stress, and supporting mitochondrial membrane integrity. Strong preclinical data; emerging human hepatoprotection studies.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'mito', 'autophagy'],
    relatedSynergySlugs: [],
    outline: [
      'Overview & proteostasis link',
      'Mechanism: UPR modulation & chaperone activity',
      'Evidence summary (preclinical + pilot human)',
      'Decision tree & stack placement',
      'Dosing protocol & compliance checklist',
      'Monitoring: liver panel, GGT',
      'Buyer guide & red flags',
      'Personal results template',
    ],
    mdxSlug: 'tudca',
  },
  {
    slug: 'grapeseed',
    category: 'compounds',
    title: 'Grape Seed Extract (95% OPC)',
    tagline: 'Antioxidant polyphenol — real RCT evidence, but meta-analyses disagree on the headline claim',
    summary:
      'Grape Seed Extract standardized to ≥95% OPC (oligomeric proanthocyanidins). A 2016 meta-analysis (16 RCTs, n=810) found a significant systolic blood pressure reduction, but a larger 2022 meta-analysis of 19 trials found no significant SBP or endothelial (FMD) effect — only diastolic BP and heart rate held up. Not a native Stack Architect compound; evaluate it as an educational deep-dive, not a plug-and-play stack addition.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'genomic', 'mito', 'communication'],
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & OPC standardization — why 95% matters',
      'Mechanisms: ROS scavenging, Nrf2, eNOS/NO, NF-κB',
      'Evidence summary — where meta-analyses agree and disagree',
      'Dosing protocol & form selection',
      'Monitoring: blood pressure, hs-CRP',
      'Safety, antiplatelet notes, interactions',
      'Personal results template',
    ],
    mdxSlug: 'grapeseed',
  },
  {
    slug: 'sulforaphane',
    category: 'compounds',
    title: 'Sulforaphane',
    tagline: 'NRF2 master regulator — 200+ cytoprotective genes',
    summary:
      'Isothiocyanate from broccoli sprouts that covalently modifies KEAP1, releasing NRF2 to drive phase-II detox, proteasome upregulation, and anti-inflammatory gene expression.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'inflammation', 'proteostasis'],
    compoundId: 'sulforaphane',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview & NRF2 pathway',
      'Mechanism: KEAP1 modification',
      'Evidence summary',
      'Dosing & myrosinase activation',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'sulforaphane',
  },
  {
    slug: 'rala',
    category: 'compounds',
    title: 'R-Alpha Lipoic Acid (R-ALA)',
    tagline: 'Mitochondrial redox recycler — NRF2 stack completion',
    summary:
      'Recycles oxidized glutathione, vitamins C and E. Cofactor for pyruvate dehydrogenase in mitochondria. Completes the NRF2 Defense Triad (substrate → signal → recycle). Tier B in healthy adults; strong mechanistic and metabolic syndrome data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'proteostasis', 'inflammation'],
    compoundId: 'rala',
    relatedSynergySlugs: ['glynac-nrf2-triad', 'nad-mito-stack'],
    outline: [
      'Overview & NRF2 triad placement',
      'Mechanism: redox recycling hub',
      'Evidence summary (neuropathy, metabolic data)',
      'Dosing protocol & enantiomer note',
      'NRF2 Defense Triad choreography',
      'Monitoring: GSH, 8-OHdG, glucose',
      'Safety & interactions',
      'Personal results template',
    ],
    mdxSlug: 'rala',
  },
  {
    slug: 'cakg',
    category: 'compounds',
    title: 'Ca-AKG (Calcium Alpha-Ketoglutarate)',
    tagline: 'Epigenetic cofactor & TCA fuel — highest hallmark breadth per gram',
    summary:
      'TCA cycle intermediate and obligate cofactor for TET, JMJ, and PHD enzymes that reverse age-related DNA and histone methylation drift. Mouse lifespan +12%; emerging human metabolic and clock data from 2024.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['epigenetic', 'mito', 'stem'],
    compoundId: 'cakg',
    relatedSynergySlugs: ['nad-mito-stack'],
    outline: [
      'Overview & AKG decline curve',
      'Mechanism: TCA anaplerosis + TET/JMJ cofactor',
      'Evidence summary (mouse lifespan + human 2024)',
      'Dosing protocol & titration',
      'NAD+ Mito Stack ramp-in schedule',
      'Monitoring: glucose, hs-CRP, epigenetic clock',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'cakg',
  },
  {
    slug: 'resveratrol',
    category: 'compounds',
    title: 'Trans-Resveratrol',
    tagline: 'SIRT1 activator — caloric restriction mimetic',
    summary:
      'Phytoalexin activating SIRT1 and AMPK. Synergistic with NAD+ precursors for epigenetic and mitochondrial remodeling. Tier B — strong mechanism, mixed human outcomes.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'inflammation', 'senescence'],
    compoundId: 'resveratrol',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1', 'nad-mito-stack'],
    outline: [
      'Overview & SIRT1 axis',
      'Mechanism & bioavailability',
      'Evidence summary',
      'Dosing & NMN pairing (PM timing)',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'resveratrol',
  },
  {
    slug: 'taurine',
    category: 'compounds',
    title: 'Taurine',
    tagline: 'Age-depleted osmolyte — Science 2023 lifespan signals',
    summary:
      'Sulfonic amino acid buffering mitochondrial stress and declining ~80% with age. Tier B: strong Singh 2023 Science mechanism and animal lifespan data; limited human longevity RCT.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic'],
    compoundId: 'taurine',
    outline: [
      'Overview & taurine decline with age',
      'Mechanism: membrane + mitochondrial buffering',
      'Evidence: Singh 2023 Science',
      'Dosing protocol',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'taurine',
  },
  {
    slug: 'spermidine',
    category: 'compounds',
    title: 'Spermidine',
    tagline: 'Autophagy polyamine — Madeo 2021 memory RCT',
    summary:
      'Dietary and supplemental polyamine inducing autophagy via EP300 inhibition. Tier B: human pilot memory outcomes; strong mechanistic autophagy data.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['autophagy', 'epigenetic', 'senescence'],
    compoundId: 'spermidine',
    outline: [
      'Overview & autophagy induction',
      'Mechanism: EP300 / eIF5A',
      'Evidence: Madeo 2021 Cell RCT',
      'Dosing & dietary sources',
      'Monitoring',
      'Personal results template',
    ],
    mdxSlug: 'spermidine',
  },
  {
    slug: 'pterostilbene',
    category: 'compounds',
    title: 'Pterostilbene',
    tagline: 'Methylated resveratrol — 4× bioavailability',
    summary:
      'Stilbenoid SIRT1 activator with superior human PK vs trans-resveratrol. Tier B: Kapetanovic 2011 safety/PK; compare with resveratrol for stack pairing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'inflammation'],
    compoundId: 'pterostilbene',
    relatedSynergySlugs: ['nmn-resveratrol-sirt1'],
    outline: [
      'Overview vs resveratrol',
      'Mechanism & bioavailability advantage',
      'Evidence summary',
      'Dosing & NMN pairing',
      'Compare table link',
      'Personal results template',
    ],
    mdxSlug: 'pterostilbene',
  },

  {
    slug: 'berberine',
    category: 'compounds',
    title: 'Berberine HCl',
    tagline: 'AMPK activator — metformin-equivalent glucose outcomes without a prescription',
    summary:
      'Isoquinoline alkaloid activating AMPK with RCT-equivalent glucose control vs metformin (500 mg TID, 13-week head-to-head). Tier A for metabolic endpoints; adds LDL/TG lipid benefits metformin lacks. Bioavailability-enhanced forms (dihydroberberine) achieve 5× plasma levels.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['nutrient', 'inflammation', 'mito', 'communication'],
    compoundId: 'berberine',
    outline: [
      'Overview & AMPK mechanism',
      'Head-to-head vs metformin (Yin 2008 RCT)',
      'Lipid and glucose evidence summary',
      'Dosing: TID vs dihydroberberine upgrade',
      'Monitoring: HbA1c, ApoB, LDL',
      'Safety & drug interactions',
      'Personal results template',
    ],
    mdxSlug: 'berberine',
  },
  {
    slug: 'urolithina',
    category: 'compounds',
    title: 'Urolithin A (Mitopure)',
    tagline: 'Mitophagy activator — Phase 2 muscle trial, Tier A',
    summary:
      'Gut-derived metabolite from ellagitannin polyphenols that activates mitophagy — the selective clearance of damaged mitochondria. Phase 2 RCT (2022, Cell Reports Medicine) confirmed improved muscle strength and reduced fatigue in adults ≥65 at 1000 mg/day. Only commercially available mitophagy-specific compound with human trial data.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'autophagy', 'senescence'],
    compoundId: 'urolithina',
    outline: [
      'Overview & mitophagy mechanism',
      'Phase 2 RCT: muscle strength + fatigue outcomes',
      'Mitopure vs pomegranate extract — why standardization matters',
      'Dosing: 500 vs 1000 mg, AM with food',
      'Monitoring: muscle function, hs-CRP',
      'Safety & contraindications',
      'Personal results template',
    ],
    mdxSlug: 'urolithina',
  },
  {
    slug: 'fisetin',
    category: 'compounds',
    title: 'Fisetin',
    tagline: 'Senolytic flavonoid — Mayo Clinic pilot, highest potency ranking',
    summary:
      'Flavonoid with the highest senolytic potency of dietary compounds tested (Kirkland lab, 2018). Mayo Clinic pilot RCT reduced p16INK4A and p21 senescence markers and improved physical function. Pulse-dose protocol (20 mg/kg × 2 consecutive days/month) is the evidence-based regimen. Tier B pending larger RCT.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'communication', 'inflammation'],
    compoundId: 'fisetin',
    outline: [
      'Overview: senolytics and the SASP problem',
      'Senolytic potency ranking vs quercetin, navitoclax',
      'Mayo Clinic pilot RCT — design and outcomes',
      'Pulse-dose protocol: why 2-day burst, not daily',
      'Monitoring: p16/p21 proxies, inflammation markers',
      'Safety — low adverse event profile',
      'Personal results template',
    ],
    mdxSlug: 'fisetin',
  },
  {
    slug: 'coq10',
    category: 'compounds',
    title: 'CoQ10 (Ubiquinol)',
    tagline: 'Electron transport chain cofactor — essential for statin users',
    summary:
      'Mitochondrial cofactor required at Complex I, II, and III of the electron transport chain. Declines ~50% by age 70. Ubiquinol (reduced form) has superior bioavailability. Meta-analysis of 17 RCTs confirms hs-CRP and IL-6 reduction. Critical for statin users — statins block HMG-CoA reductase, which also synthesizes CoQ10. Tier B.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic'],
    compoundId: 'coq10',
    outline: [
      'Overview: CoQ10 in the ETC',
      'Age-related decline and statin depletion',
      'Ubiquinol vs ubiquinone — bioavailability data',
      'Meta-analysis: 17 RCTs on inflammation markers',
      'Dosing: 100–300 mg ubiquinol, fat co-ingestion required',
      'Monitoring: CoQ10 plasma, hs-CRP, energy',
      'Personal results template',
    ],
    mdxSlug: 'coq10',
  },
  {
    slug: 'omega3',
    category: 'compounds',
    title: 'Omega-3 (EPA + DHA)',
    tagline: 'REDUCE-IT: 25% CV event reduction — SPM resolution axis',
    summary:
      'EPA and DHA serve as precursors to specialized pro-resolving mediators (SPMs) — resolvins and protectins — that actively resolve inflammation rather than merely suppressing it. REDUCE-IT trial (NEJM 2018, n=8,179): high-dose EPA (4 g/day) reduced major CV events 25% in high-risk patients. Tier A across cardiovascular, inflammatory, and microbiome endpoints.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['inflammation', 'communication', 'telomeres', 'dysbiosis'],
    compoundId: 'omega3',
    outline: [
      'Overview: EPA/DHA vs ALA — why conversion matters',
      'SPM resolution axis — active resolution, not suppression',
      'REDUCE-IT trial design and outcomes',
      'Telomere data: omega-3 and telomerase activation',
      'Dosing: 2–4 g EPA+DHA combined; form (rTG, krill, standard)',
      'Monitoring: omega-3 index, hs-CRP, ApoB, triglycerides',
      'Personal results template',
    ],
    mdxSlug: 'omega3',
  },
  {
    slug: 'creatine',
    category: 'compounds',
    title: 'Creatine Monohydrate',
    tagline: 'The most-validated ergogenic — and a real anti-sarcopenia healthspan lever',
    summary:
      'Creatine monohydrate raises muscle phosphocreatine, buffering ATP regeneration. Decades of RCTs show it increases lean mass and strength when paired with resistance training — Tier A for muscle/strength, the clearest human evidence of any compound here. For a longevity audience the payoff is anti-sarcopenia muscle preservation; cognition and longevity endpoints are honest Tier B. 3–5 g/day, daily, no loading required.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'stem', 'communication', 'proteostasis'],
    compoundId: 'creatine',
    outline: [
      'Overview: phosphocreatine energy buffer — and why it belongs in a longevity library',
      'Mechanism: creatine kinase, satellite cells, brain bioenergetics',
      'Evidence summary — Tier A muscle/strength, Tier B cognition/longevity',
      'Dosing: 3–5 g/day, loading optional, monohydrate only',
      'Monitoring: lean mass, strength, and the creatinine-vs-cystatin-C caveat',
      'Safety & the kidney-lab misread',
      'Personal results template',
    ],
    mdxSlug: 'creatine',
  },
  {
    slug: 'quercetin',
    category: 'compounds',
    title: 'Quercetin',
    tagline: 'Senolytic only as the "Q" in D+Q — weak solo, useful as an anti-inflammatory adjunct',
    summary:
      'Quercetin is a flavonoid whose strongest human senolytic evidence is for the combination Dasatinib + Quercetin (D+Q), not quercetin alone: D+Q reduced senescent-cell burden in human adipose tissue and showed feasibility in IPF and diabetic-kidney pilots. Solo OTC quercetin is a weak standalone senolytic with poor bioavailability. Tier B — a physician-supervised senolytic pairing or an anti-inflammatory/antihistamine adjunct, not a substitute for dasatinib.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['senescence', 'inflammation', 'communication'],
    compoundId: 'quercetin',
    outline: [
      'Overview: the "Q" in the D+Q senolytic protocol',
      'Mechanism: senolysis with dasatinib, NF-κB, mast-cell stabilization',
      'Evidence summary — combination vs solo, honestly separated',
      'Dosing: bioavailability (isoquercetin / piperine) and the D+Q caveat',
      'Monitoring: hs-CRP and inflammatory load',
      'Safety: CYP3A4 and antiplatelet interactions',
      'Personal results template',
    ],
    mdxSlug: 'quercetin',
  },
  {
    slug: 'curcumin',
    category: 'compounds',
    title: 'Curcumin',
    tagline: 'Real NF-κB anti-inflammatory — but bioavailability decides everything',
    summary:
      'Curcumin (from turmeric) works mainly by dampening NF-κB and COX-2, not by strongly activating NRF2. It has genuine human RCT evidence for osteoarthritis and inflammatory markers, but the hs-CRP literature is mixed and dominated by formulation: native curcumin is poorly absorbed, so piperine/phytosome/nano forms decide whether the dose does anything. Tier B anti-inflammatory adjunct — not a substitute for sulforaphane\'s KEAP1/NRF2 activation.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'communication', 'genomic'],
    compoundId: 'curcumin',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview: NF-κB dampening — and the bioavailability catch',
      'Mechanism: NF-κB, COX-2, weak NRF2',
      'Evidence summary — osteoarthritis and the mixed CRP meta-analyses',
      'Dosing: form first (piperine / phytosome / nano)',
      'Monitoring: hs-CRP and joint function',
      'Safety: antiplatelet, bile, and iron interactions',
      'Personal results template',
    ],
    mdxSlug: 'curcumin',
  },
  {
    slug: 'glycine',
    category: 'compounds',
    title: 'Glycine',
    tagline: 'The "Gly" in GlyNAC — plus a real, cheap sleep-quality effect',
    summary:
      'Glycine is a rate-contributing substrate for glutathione synthesis, the dominant amino acid in collagen, and an inhibitory neurotransmitter with human sleep-quality data. Its biggest longevity role is as half of GlyNAC — cysteine repletion alone does not restore aging glutathione. Tier B; cheap, very safe, ~3 g/day.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'communication', 'inflammation'],
    compoundId: 'glycine',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview: three roles — glutathione, collagen, sleep',
      'Mechanism: GSH substrate, ECM, inhibitory neurotransmission',
      'Evidence summary — GlyNAC and sleep RCTs',
      'Dosing: glutathione support vs sleep timing',
      'Monitoring: sleep quality, GSH (if paired)',
      'Safety: the clozapine interaction',
      'Personal results template',
    ],
    mdxSlug: 'glycine',
  },
  {
    slug: 'nac',
    category: 'compounds',
    title: 'N-Acetylcysteine (NAC)',
    tagline: 'Approved-drug cysteine donor — but incomplete for aging glutathione without glycine',
    summary:
      'NAC is an approved mucolytic and the acetaminophen-overdose antidote, working by replenishing glutathione\'s rate-limiting cysteine substrate. The GlyNAC trials showed NAC alone doesn\'t fully restore aging glutathione — glycine has to come with it. Tier B for longevity use; 600–1200 mg/day, ideally paired with glycine.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'inflammation', 'genomic'],
    compoundId: 'nac',
    relatedSynergySlugs: ['glynac-nrf2-triad'],
    outline: [
      'Overview: approved-drug pharmacology meets aging biology',
      'Mechanism: cysteine → glutathione substrate',
      'Evidence summary — the NAC-alone trap (GlyNAC)',
      'Dosing: pairing with glycine',
      'Monitoring: GSH and oxidative markers',
      'Safety: nitroglycerin and anticoagulant interactions',
      'Personal results template',
    ],
    mdxSlug: 'nac',
  },
  {
    slug: 'vitamin-d3',
    category: 'compounds',
    title: 'Vitamin D3',
    tagline: 'A hormone precursor — and the VITAL trial\'s honest reset on megadosing',
    summary:
      'Vitamin D3 regulates immune, bone, and muscle signaling via the vitamin D receptor. The landmark VITAL trial (Manson et al., NEJM 2019, n=25,871) found no reduction in overall cancer/CVD incidence for unselected adults, but did find fewer autoimmune diagnoses and a cancer-mortality signal. Correcting a real deficiency is well supported; megadosing replete adults is not. Tier B; test 25(OH)D before dosing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'communication', 'stem'],
    compoundId: 'vitamin-d3',
    outline: [
      'Overview: hormone precursor, and the VITAL-trial reset',
      'Mechanism: VDR gene regulation across tissues',
      'Evidence summary — what VITAL found and didn\'t find',
      'Dosing: test first, correct deficiency, then maintain',
      'Monitoring: 25(OH)D and calcium',
      'Safety: hypercalcemia and granulomatous-disease risk',
      'Personal results template',
    ],
    mdxSlug: 'vitamin-d3',
  },
  {
    slug: 'magnesium',
    category: 'compounds',
    title: 'Magnesium (Glycinate / Threonate)',
    tagline: 'Cofactor for 300+ enzymes — including the ones that activate vitamin D',
    summary:
      'Magnesium is required for ATP-generating enzymes, DNA repair, and converting vitamin D to its active hormone form. Human RCTs support sleep quality and modest blood-pressure benefit, concentrated in people with low baseline status. Glycinate is the best-tolerated general form; threonate has specific human data for raising brain magnesium. Tier B; 200–400 mg elemental/day.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'communication', 'inflammation'],
    compoundId: 'magnesium',
    outline: [
      'Overview: 300+ enzyme cofactor, including vitamin D activation',
      'Mechanism: ATP synthesis, NMDA/neuromuscular signaling',
      'Evidence summary — sleep, blood pressure, and the threonate cognition data',
      'Dosing: form selection by goal (glycinate vs threonate)',
      'Monitoring: sleep quality and blood pressure',
      'Safety: kidney disease and antibiotic spacing',
      'Personal results template',
    ],
    mdxSlug: 'magnesium',
  },
  {
    slug: 'collagen-peptides',
    category: 'compounds',
    title: 'Collagen Peptides',
    tagline: 'Modest, slow, replicated — real RCT data for skin and joints, not a transformation',
    summary:
      'Hydrolyzed collagen peptides supply glycine-proline-hydroxyproline fragments shown in placebo-controlled RCTs to modestly improve skin elasticity/hydration (Proksch et al. 2014) and activity-related joint pain (Clark et al. 2008). Effects are real but small and slow (8–12+ weeks) — a complement to, not a substitute for, resistance training\'s much larger effect on connective tissue. Tier B; 10–15 g/day.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'stem'],
    compoundId: 'collagen-peptides',
    outline: [
      'Overview: signaling peptides, not just amino-acid supply',
      'Mechanism: fibroblast/chondrocyte stimulation',
      'Evidence summary — skin elasticity and joint-pain RCTs',
      'Dosing: 10–15 g/day, paired with vitamin C',
      'Monitoring: skin/joint function over 8–12 weeks',
      'Safety: sourcing and allergy notes',
      'Personal results template',
    ],
    mdxSlug: 'collagen-peptides',
  },
  {
    slug: 'glucosamine',
    category: 'compounds',
    title: 'Glucosamine Sulfate',
    tagline: 'Real joint-symptom RCT evidence in the right form and population — plus an observational mortality signal',
    summary:
      'Glucosamine sulfate (not hydrochloride) showed benefit in the GAIT trial\'s moderate-to-severe pain subgroup and in European 3-year crystalline-sulfate trials. A large UK Biobank cohort (Ma et al., BMJ 2019, n≈466,000) found lower all-cause/CV mortality in regular users — a striking but purely observational association. Tier B; use for joint symptoms with realistic expectations, not as a proven longevity intervention alone.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'inflammation'],
    compoundId: 'glucosamine',
    outline: [
      'Overview: form and severity decide whether trials show benefit',
      'Mechanism: cartilage matrix substrate',
      'Evidence summary — GAIT, European trials, and the BMJ cohort',
      'Dosing: sulfate form, 1500 mg/day',
      'Monitoring: joint pain and function',
      'Safety: shellfish sourcing and warfarin interaction',
      'Personal results template',
    ],
    mdxSlug: 'glucosamine',
  },
  {
    slug: 'astaxanthin',
    category: 'compounds',
    title: 'Astaxanthin',
    tagline: 'Membrane-spanning carotenoid antioxidant — dose matters more than the marketing suggests',
    summary:
      'Astaxanthin spans the full cell membrane, quenching ROS at both hydrophilic and hydrophobic faces. Human RCTs at 4-12 mg/day show benefits for skin photoaging, eye/visual fatigue, and exercise-oxidative-stress markers — well above the ~2 mg found in most krill oil capsules. Tier B; a real adjunct antioxidant, not a foundation compound.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'mito', 'proteostasis'],
    compoundId: 'astaxanthin',
    outline: [
      'Overview: membrane-spanning carotenoid structure',
      'Mechanism: dual-compartment ROS quenching',
      'Evidence summary — skin, eye fatigue, exercise recovery RCTs',
      'Dosing: 4-12 mg/day (the therapeutic range, not krill oil\'s ~2 mg)',
      'Monitoring: skin appearance and visual fatigue',
      'Safety: antiplatelet caution',
      'Personal results template',
    ],
    mdxSlug: 'astaxanthin',
  },
  {
    slug: 'egcg',
    category: 'compounds',
    title: 'EGCG (Green Tea Catechin)',
    tagline: 'Real AMPK-overlapping metabolic benefit — with a regulator-flagged high-dose liver risk',
    summary:
      'EGCG activates AMPK (overlapping berberine/metformin) and shows modest metabolic benefit in human trials. The essential caveat: concentrated supplemental EGCG at high doses, especially fasted, carries a genuine EFSA-acknowledged hepatotoxicity signal that brewed tea\'s safety record does not share. Tier B; prefer brewed tea or moderate-dose extracts with food.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['nutrient', 'inflammation', 'mito'],
    compoundId: 'egcg',
    outline: [
      'Overview: the dose that matters — brewed tea vs concentrated extract',
      'Mechanism: AMPK activation, lipid metabolism',
      'Evidence summary — metabolic benefit and the hepatotoxicity signal',
      'Dosing: brewed tea preferred; conservative extract dosing with food',
      'Monitoring: LDL and liver enzymes if using an extract',
      'Safety: the concentrated fasted-dose liver-injury pattern',
      'Personal results template',
    ],
    mdxSlug: 'egcg',
  },
  {
    slug: 'zinc',
    category: 'compounds',
    title: 'Zinc',
    tagline: 'A correction mineral, not a megadose one — real cold-duration RCT evidence',
    summary:
      'Zinc lozenges started within 24 hours of cold onset shorten symptom duration (Cochrane review) — genuine, replicated human evidence for a specific use. Chronic excess zinc causes copper deficiency and can itself impair immunity, so this is a deficiency-correction compound, not a "more is better" one. Tier B; 15-30 mg/day, balanced with copper.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'proteostasis'],
    compoundId: 'zinc',
    outline: [
      'Overview: immune cofactor and the cold-duration evidence',
      'Mechanism: immune-cell function, enzyme cofactor, wound healing',
      'Evidence summary — Cochrane cold-duration data vs broader claims',
      'Dosing: 15-30 mg/day maintenance; lozenges for active colds',
      'Monitoring: serum zinc/copper with chronic use',
      'Safety: the copper-deficiency risk of chronic excess zinc',
      'Personal results template',
    ],
    mdxSlug: 'zinc',
  },
  {
    slug: 'selenium',
    category: 'compounds',
    title: 'Selenium',
    tagline: 'The SELECT trial corrected its cancer-prevention reputation — still real for deficiency',
    summary:
      'Selenium is a glutathione-peroxidase and thyroid-hormone cofactor. The large SELECT trial (Lippman et al., JAMA 2009, n≈ 35,500) found selenium did not reduce prostate cancer risk, correcting an earlier "cancer-prevention supplement" reputation. Selenium remains genuinely important for correcting real deficiency. Tier B; test before megadosing — the safety margin is narrower than most minerals.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['inflammation', 'communication'],
    compoundId: 'selenium',
    outline: [
      'Overview: the SELECT trial correction',
      'Mechanism: glutathione peroxidase, thyroid hormone activation',
      'Evidence summary — what SELECT found (and refuted)',
      'Dosing: test first, 55-100 mcg/day maintenance',
      'Monitoring: serum selenium and thyroid panel',
      'Safety: selenosis and the narrow safety margin',
      'Personal results template',
    ],
    mdxSlug: 'selenium',
  },
  {
    slug: 'vitamin-k2',
    category: 'compounds',
    title: 'Vitamin K2 (MK-7)',
    tagline: 'Directs the calcium vitamin D3 helps you absorb toward bone, not arteries',
    summary:
      'Vitamin K2 (MK-7) activates matrix Gla protein, which inhibits arterial calcium deposition and supports bone mineralization. The Rotterdam Study found higher dietary K2 associated with less coronary calcification and lower CV mortality; smaller RCTs show slowed arterial-stiffness progression. Tier B; a rational D3 pairing, though hard-endpoint RCT confirmation is still developing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'inflammation'],
    compoundId: 'vitamin-k2',
    outline: [
      'Overview: MK-7 vs K1, and matrix Gla protein',
      'Mechanism: MGP and osteocalcin activation',
      'Evidence summary — Rotterdam Study and arterial-stiffness RCTs',
      'Dosing: 90-180 mcg/day, paired with D3',
      'Monitoring: coronary calcium score and bone density if obtained',
      'Safety: the warfarin interaction (critical)',
      'Personal results template',
    ],
    mdxSlug: 'vitamin-k2',
  },
  {
    slug: 'tmg',
    category: 'compounds',
    title: 'TMG (Trimethylglycine / Betaine)',
    tagline: 'Reliably lowers homocysteine — but lowering the biomarker isn\'t proven to lower events',
    summary:
      'TMG donates a methyl group to convert homocysteine back to methionine, reliably lowering elevated homocysteine. The important caveat: HOPE-2 (Lonn et al., NEJM 2006) showed a different homocysteine-lowering combination reduced the biomarker without reducing cardiovascular events. Tier B; a real biomarker-correction tool for genuinely elevated homocysteine, not a proven event-reduction intervention.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['epigenetic', 'inflammation', 'genomic'],
    compoundId: 'tmg',
    outline: [
      'Overview: the BHMT methyl-donor pathway',
      'Mechanism: homocysteine remethylation, SAMe pool support',
      'Evidence summary — reliable biomarker effect vs the HOPE-2 outcome gap',
      'Dosing: 1-3 g/day, best for a measured elevated homocysteine',
      'Monitoring: homocysteine, B12, and folate',
      'Safety: check B12/folate first',
      'Personal results template',
    ],
    mdxSlug: 'tmg',
  },
  {
    slug: 'boron',
    category: 'compounds',
    title: 'Boron',
    tagline: 'Plausible hormone/bone trace mineral — the evidence base is genuinely thin',
    summary:
      'Boron shows modest effects on free testosterone, estradiol, and joint comfort in small human trials, plus a proposed role in vitamin D metabolism and bone mineralization. The evidence base is smaller and less rigorous than most compounds in this library. Tier C; low-risk, low-priority — reasonable to try, shouldn\'t displace Tier A/B foundations.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['proteostasis', 'communication'],
    compoundId: 'boron',
    outline: [
      'Overview: an under-studied but plausible trace mineral',
      'Mechanism: steroid hormone and vitamin D metabolism (proposed)',
      'Evidence summary — small trials, honestly framed',
      'Dosing: 3-6 mg/day',
      'Monitoring: hormone markers and joint comfort',
      'Safety: staying within supplemental ranges',
      'Personal results template',
    ],
    mdxSlug: 'boron',
  },
  {
    slug: 'pqq',
    category: 'compounds',
    title: 'PQQ (Pyrroloquinoline Quinone)',
    tagline: 'Mitochondrial-biogenesis mechanism in urolithin A\'s territory — with far less human data',
    summary:
      'PQQ activates PGC-1α signaling and mitochondrial biogenesis in cell and animal models, with a favorable redox-cycling profile. Human evidence is limited to small early trials on cognitive and inflammatory markers — far thinner than urolithin A\'s Phase 2 RCT or CoQ10\'s meta-analyses. Tier C; a reasonable adjunct experiment once the higher-evidence mitochondrial compounds are in place, not a starting point.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['mito'],
    compoundId: 'pqq',
    relatedSynergySlugs: ['nad-mito-stack'],
    outline: [
      'Overview: redox-cycling molecule, PGC-1α activator',
      'Mechanism: mitochondrial biogenesis signaling',
      'Evidence summary — preclinical strength vs thin human data',
      'Dosing: 10-20 mg/day',
      'Monitoring: subjective energy and cognition',
      'Safety: treat as exploratory',
      'Personal results template',
    ],
    mdxSlug: 'pqq',
  },
  {
    slug: 'ashwagandha',
    category: 'compounds',
    title: 'Ashwagandha (KSM-66 / Withania somnifera)',
    tagline: 'One of the better-evidenced adaptogens — real cortisol and stress-questionnaire RCT data',
    summary:
      'Standardized ashwagandha extracts (KSM-66, Sensoril) show replicated reductions in serum cortisol and validated stress/anxiety scores over 8-12 weeks — one of the more consistently evidenced adaptogenic herbs. Raw root powder is a different, less-characterized product. Tier B; 300-600 mg/day standardized extract.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication', 'inflammation'],
    compoundId: 'ashwagandha',
    outline: [
      'Overview: adaptogen with an actual RCT base',
      'Mechanism: HPA-axis / cortisol modulation',
      'Evidence summary — KSM-66 and Sensoril trials',
      'Dosing: 300-600 mg/day standardized extract',
      'Monitoring: subjective stress and cortisol',
      'Safety: thyroid and pregnancy caveats',
      'Personal results template',
    ],
    mdxSlug: 'ashwagandha',
  },
  {
    slug: 'l-theanine',
    category: 'compounds',
    title: 'L-Theanine',
    tagline: 'EEG-confirmed alpha-wave calm without sedation — best paired with caffeine',
    summary:
      'L-theanine reliably increases alpha-wave EEG activity within ~40 minutes without causing drowsiness. Its best-replicated real-world use is paired with caffeine, smoothing jitteriness while preserving focus. Tier B; 100-200 mg, often 1:1-2:1 with caffeine.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication'],
    compoundId: 'l-theanine',
    outline: [
      'Overview: EEG alpha-wave relaxation without sedation',
      'Mechanism: glutamate/GABA modulation, caffeine synergy',
      'Evidence summary — alpha-wave and caffeine-pairing RCTs',
      'Dosing: 100-200 mg, caffeine ratio',
      'Monitoring: subjective focus and jitteriness',
      'Safety: mild blood-pressure effect',
      'Personal results template',
    ],
    mdxSlug: 'l-theanine',
  },
  {
    slug: 'rhodiola',
    category: 'compounds',
    title: 'Rhodiola Rosea',
    tagline: 'Fatigue and stress-performance adaptogen — real but more heterogeneous evidence than ashwagandha',
    summary:
      'Standardized rhodiola extracts (rosavins + salidroside) show reduced fatigue and improved mental performance under sustained stress in placebo-controlled RCTs, most reliably in stress/burnout populations. The evidence base is real but more heterogeneous (varied extracts/doses) than ashwagandha\'s. Tier B; 200-400 mg/day standardized extract.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication', 'mito'],
    compoundId: 'rhodiola',
    outline: [
      'Overview: stress-fatigue adaptogen',
      'Mechanism: HPA-axis modulation, fatigue reduction',
      'Evidence summary — fatigue and cognitive-performance RCTs',
      'Dosing: 200-400 mg/day standardized extract',
      'Monitoring: subjective fatigue and focus',
      'Safety: bipolar disorder and stimulant caveats',
      'Personal results template',
    ],
    mdxSlug: 'rhodiola',
  },
  {
    slug: 'lions-mane',
    category: 'compounds',
    title: "Lion's Mane (Hericium erinaceus)",
    tagline: 'A real, single small human RCT on NGF-linked cognitive support — genuinely early-stage',
    summary:
      'Lion\'s Mane stimulates nerve growth factor (NGF) synthesis in preclinical models. One small placebo-controlled human RCT (Mori et al. 2009, n=30, older adults with mild cognitive impairment) found improved cognitive scores that reversed after stopping — a real, published signal awaiting broader replication. Tier C; low-risk, reasonable to try, not yet established.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['communication'],
    compoundId: 'lions-mane',
    outline: [
      'Overview: NGF-stimulating mushroom compound',
      'Mechanism: nerve growth factor synthesis (preclinical)',
      'Evidence summary — the Mori 2009 trial, honestly scoped',
      'Dosing: 500-1000 mg/day fruiting-body extract',
      'Monitoring: subjective cognitive function',
      'Safety: allergy and anticoagulant notes',
      'Personal results template',
    ],
    mdxSlug: 'lions-mane',
  },
  {
    slug: 'bacopa',
    category: 'compounds',
    title: 'Bacopa Monnieri',
    tagline: 'The most consistently replicated cognitive-support botanical — but slow (8-12+ weeks)',
    summary:
      'Standardized bacopa extracts (≥50% bacosides) improve memory-formation and recall performance across multiple independent RCTs and a meta-analysis, with the effect consistently absent at 4 weeks and emerging by 8-12 weeks. Tier B; one of the better-evidenced cognitive botanicals, with a genuinely slow, cumulative effect timeline.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication'],
    compoundId: 'bacopa',
    outline: [
      'Overview: Ayurvedic herb with the deepest cognitive RCT base here',
      'Mechanism: neuronal signaling modulation, antioxidant activity',
      'Evidence summary — multi-trial and meta-analysis consistency',
      'Dosing: 300 mg/day standardized extract (≥50% bacosides)',
      'Monitoring: memory/recall, minimum 12-week commitment',
      'Safety: thyroid and sedative interaction notes',
      'Personal results template',
    ],
    mdxSlug: 'bacopa',
  },
  {
    slug: 'dhea',
    category: 'compounds',
    title: 'DHEA',
    tagline: 'An 80%-by-70 hormone decline that restoration hasn\'t been shown to fix',
    summary:
      'DHEA declines roughly 80% from young adulthood to age 70, but the DHEAge study (Baulieu et al., PNAS 2000) and similar RCTs found restoring it in healthy older adults produced only modest, inconsistent effects — not the broad vitality/cognition benefit the decline curve implies. Tier C; a genuine hormone requiring physician-guided use and lab monitoring, not a self-directed supplement.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['communication'],
    compoundId: 'dhea',
    outline: [
      'Overview: the decline curve vs the restoration-trial reality',
      'Mechanism: peripheral steroid hormone conversion',
      'Evidence summary — the DHEAge study\'s honest null result',
      'Dosing: test-first, physician-directed only',
      'Monitoring: DHEA-S and hormone-sensitive symptoms',
      'Safety: hormone-sensitive cancer contraindication',
      'Personal results template',
    ],
    mdxSlug: 'dhea',
  },
  {
    slug: 'melatonin',
    category: 'compounds',
    title: 'Melatonin',
    tagline: 'A circadian signal, not a sedative — and lower doses work as well as higher ones',
    summary:
      'Melatonin modestly reduces sleep-onset latency and is most clearly effective for circadian realignment (jet lag, shift work). Dose-response data consistently shows no added benefit above 0.5-5 mg, well below the 5-10 mg doses commonly sold. Tier B; low-dose, well-timed use, not a general sleep-quality booster.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication'],
    compoundId: 'melatonin',
    outline: [
      'Overview: circadian signal vs sedative — and the dose most products get wrong',
      'Mechanism: SCN circadian phase signaling',
      'Evidence summary — sleep-onset and jet lag/shift-work trials',
      'Dosing: 0.5-3 mg, timed correctly',
      'Monitoring: sleep-onset latency and next-day grogginess',
      'Safety: anticoagulant and immunosuppressant interactions',
      'Personal results template',
    ],
    mdxSlug: 'melatonin',
  },
  {
    slug: 'probiotics',
    category: 'compounds',
    title: 'Probiotics (Targeted, Strain-Specific)',
    tagline: 'TNiC\'s own dysbiosis data favors fiber and fermented foods over generic multi-strain blends',
    summary:
      'Probiotic evidence is entirely strain-specific — L. rhamnosus GG has real RCT support for antibiotic-associated diarrhea, but general "gut health" multi-strain blends have weak, inconsistent support. TNiC\'s own reviewed evidence (Wastyk et al., Cell 2021, PMID 34432955) found fermented foods outperformed a matched high-fiber diet for inflammatory and diversity outcomes. Tier B; match the strain to the use case, or go food-first.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['dysbiosis', 'inflammation'],
    compoundId: 'probiotics',
    outline: [
      'Overview: why strain-specificity is the whole story',
      'Mechanism: microbiome diversity/SCFA vs single-strain colonization',
      'Evidence summary — the Wastyk 2021 fermented-food comparison',
      'Dosing: strain-matched use cases vs food-first default',
      'Monitoring: digestive symptoms and hs-CRP',
      'Safety: immunocompromised-population caution',
      'Personal results template',
    ],
    mdxSlug: 'probiotics',
  },
  {
    slug: 'inositol',
    category: 'compounds',
    title: 'Inositol (Myo-Inositol)',
    tagline: 'The library\'s strongest condition-specific evidence base — PCOS insulin sensitivity and ovulation',
    summary:
      'Myo-inositol (often with D-chiro-inositol at 40:1) has one of the more consistent human RCT bases in this library, specifically for PCOS — improving insulin sensitivity and restoring ovulatory function. Outside PCOS, general insulin-sensitivity and mood evidence is real but thinner. Tier B; strongest case is condition-specific, a reasonable adjunct elsewhere.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['nutrient', 'communication'],
    compoundId: 'inositol',
    outline: [
      'Overview: myo:D-chiro ratio and insulin signaling',
      'Mechanism: second-messenger precursor downstream of the insulin receptor',
      'Evidence summary — PCOS RCTs and meta-analyses',
      'Dosing: 2-4 g/day, 40:1 ratio for PCOS',
      'Monitoring: fasting insulin/HOMA-IR and cycle regularity',
      'Safety: glucose-lowering medication interaction',
      'Personal results template',
    ],
    mdxSlug: 'inositol',
  },
  {
    slug: 'alpha-gpc',
    category: 'compounds',
    title: 'Alpha-GPC',
    tagline: 'A bioavailable choline source with real cognitive/performance data — and an honest TMAO caveat',
    summary:
      'Alpha-GPC is an approved cognitive-decline drug in some countries, backed by RCTs in vascular cognitive impairment and post-stroke populations, plus acute growth-hormone/power-output effects in athletes. A debated observational literature links high choline intake broadly (via the TMAO metabolite) to stroke risk in some cohorts — disclosed here rather than omitted. Tier B; 300-600 mg/day, moderate and purposeful dosing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication'],
    compoundId: 'alpha-gpc',
    outline: [
      'Overview: acetylcholine precursor with dual cognitive/performance evidence',
      'Mechanism: blood-brain-barrier choline delivery',
      'Evidence summary — cognitive RCTs, athlete trials, and the TMAO literature',
      'Dosing: 300-600 mg/day',
      'Monitoring: subjective cognition and performance',
      'Safety: cardiovascular-history caveat',
      'Personal results template',
    ],
    mdxSlug: 'alpha-gpc',
  },
  {
    slug: 'vitamin-b12',
    category: 'compounds',
    title: 'Vitamin B12 (Methylcobalamin)',
    tagline: 'A correctable deficiency that rises with age — and with metformin or acid-reducer use',
    summary:
      'B12 absorption declines with age and is directly impaired by metformin and acid-reducing medication, making deficiency a genuinely under-recognized cause of fatigue, cognitive symptoms, and elevated homocysteine in older adults. Correction in deficient individuals is well-established clinical evidence. Tier B; test if on metformin, PPIs, or 60+.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['genomic', 'communication', 'inflammation'],
    compoundId: 'vitamin-b12',
    outline: [
      'Overview: why deficiency risk rises with age',
      'Mechanism: DNA synthesis, homocysteine clearance, myelin maintenance',
      'Evidence summary — deficiency correction vs replete supplementation',
      'Dosing: test first, methylcobalamin 500-1000 mcg/day',
      'Monitoring: serum B12, MMA, homocysteine',
      'Safety: masking folate deficiency',
      'Personal results template',
    ],
    mdxSlug: 'vitamin-b12',
  },
  {
    slug: 'folate',
    category: 'compounds',
    title: 'Folate (5-MTHF)',
    tagline: 'The active form that bypasses the MTHFR conversion step a lot of people are inefficient at',
    summary:
      '5-MTHF (L-methylfolate) skips the MTHFR enzyme conversion step folic acid requires, making it more reliably usable regardless of MTHFR genotype. Deficiency correction and pregnancy-relevant use are well-established; like TMG and B12, HOPE-2 showed lowering homocysteine with a folate combination didn\'t reduce cardiovascular events. Tier B.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['genomic', 'epigenetic', 'inflammation'],
    compoundId: 'folate',
    outline: [
      'Overview: why 5-MTHF over folic acid for most people',
      'Mechanism: DNA synthesis, methylation, homocysteine clearance',
      'Evidence summary — deficiency correction vs the HOPE-2 outcome gap',
      'Dosing: 400-800 mcg/day 5-MTHF, paired with B12',
      'Monitoring: folate and homocysteine',
      'Safety: the methotrexate interaction',
      'Personal results template',
    ],
    mdxSlug: 'folate',
  },
  {
    slug: 'vitamin-c',
    category: 'compounds',
    title: 'Vitamin C (Ascorbic Acid)',
    tagline: 'An obligate collagen-synthesis cofactor — modest, not magic, for immune claims',
    summary:
      'Vitamin C is an obligate enzymatic cofactor for collagen crosslinking (prolyl/lysyl hydroxylase) — Tier A-solid structural biochemistry. Cochrane review data shows regular supplementation modestly shortens cold duration but doesn\'t meaningfully prevent colds, a much smaller effect than its popular reputation. Tier B; 250-1000 mg/day covers essentially all evidence-backed use.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['proteostasis', 'inflammation'],
    compoundId: 'vitamin-c',
    outline: [
      'Overview: the collagen cofactor role vs the megadose mythology',
      'Mechanism: prolyl/lysyl hydroxylase, antioxidant, iron absorption',
      'Evidence summary — Cochrane cold-duration data',
      'Dosing: 250-500 mg/day, paired with collagen peptides',
      'Monitoring: skin/wound healing if paired with collagen',
      'Safety: kidney stone and iron-overload caveats',
      'Personal results template',
    ],
    mdxSlug: 'vitamin-c',
  },
  {
    slug: 'vitamin-e',
    category: 'compounds',
    title: 'Vitamin E (Mixed Tocopherols)',
    tagline: 'The SELECT trial found high-dose alpha-tocopherol increased prostate cancer risk',
    summary:
      'The same SELECT trial that corrected selenium\'s reputation found high-dose synthetic alpha-tocopherol (400 IU/day) modestly increased prostate cancer risk. Dietary vitamin E from food remains associated with good health; isolated high-dose supplementation does not have outcome-trial support. Tier C; correct dietary gaps, don\'t megadose.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['mito', 'inflammation'],
    compoundId: 'vitamin-e',
    outline: [
      'Overview: the SELECT trial\'s uncomfortable finding',
      'Mechanism: lipid-phase antioxidant, vitamin C recycling',
      'Evidence summary — dietary benefit vs isolated high-dose risk',
      'Dosing: food sources over high-dose isolated supplements',
      'Monitoring: dietary intake review',
      'Safety: the high-dose cancer-risk signal',
      'Personal results template',
    ],
    mdxSlug: 'vitamin-e',
  },
  {
    slug: 'iodine',
    category: 'compounds',
    title: 'Iodine',
    tagline: 'Both deficiency and excess cause thyroid dysfunction — a genuine Goldilocks nutrient',
    summary:
      'Iodine is required for thyroid hormone synthesis, and both too little and too much cause thyroid dysfunction — especially in people with undiagnosed thyroid autoimmunity. Deficiency correction is well-established essential medicine; high-dose kelp/iodine "thyroid support" supplements carry a real, documented risk of triggering dysfunction. Tier B; test before megadosing.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['communication'],
    compoundId: 'iodine',
    outline: [
      'Overview: the bidirectional deficiency/excess risk',
      'Mechanism: thyroid peroxidase, T4/T3 synthesis',
      'Evidence summary — deficiency correction vs excess-triggered dysfunction',
      'Dosing: dietary sufficiency first, physician-guided correction if deficient',
      'Monitoring: TSH before and during high-dose use',
      'Safety: the thyroid-autoimmunity trigger risk',
      'Personal results template',
    ],
    mdxSlug: 'iodine',
  },
  {
    slug: 'chromium',
    category: 'compounds',
    title: 'Chromium Picolinate',
    tagline: 'A heavily marketed "blood sugar support" mineral whose trial record is genuinely mixed',
    summary:
      'Chromium picolinate\'s glycemic and weight-loss evidence is inconsistent across meta-analyses — some small trials show modest benefit in diabetic populations, larger trials often show no significant effect. The trial record is considerably weaker than the compound\'s popular reputation. Tier C; low-risk, low-priority — berberine has substantially stronger evidence for the same goal.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['nutrient'],
    compoundId: 'chromium',
    outline: [
      'Overview: why the evidence is weaker than the marketing suggests',
      'Mechanism: proposed insulin-signaling enhancement (mechanism debated)',
      'Evidence summary — mixed glycemic meta-analyses',
      'Dosing: 200-1000 mcg/day if trying it',
      'Monitoring: fasting glucose/HbA1c',
      'Safety: kidney/liver disease caution',
      'Personal results template',
    ],
    mdxSlug: 'chromium',
  },
  {
    slug: 'mct-oil',
    category: 'compounds',
    title: 'MCT Oil (Medium-Chain Triglycerides)',
    tagline: 'The most reliable non-fasting way to raise ketones — GI tolerance is the real limiting factor',
    summary:
      'MCT oil bypasses normal fat digestion and goes directly to the liver, where it\'s reliably converted to ketones independent of carbohydrate intake — well-established, reproducible physiology. Cognitive-benefit evidence is promising but earlier-stage. Tier B; 1-2 tbsp/day, titrated slowly to avoid GI upset.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'communication'],
    compoundId: 'mct-oil',
    outline: [
      'Overview: direct hepatic delivery and ketone production',
      'Mechanism: bypassed digestion, hepatic beta-oxidation',
      'Evidence summary — reliable ketone elevation vs thinner cognitive data',
      'Dosing: titrate from 1 tsp to 1-2 tbsp/day',
      'Monitoring: ketones and GI tolerance',
      'Safety: liver disease caution',
      'Personal results template',
    ],
    mdxSlug: 'mct-oil',
  },
  {
    slug: 'beta-alanine',
    category: 'compounds',
    title: 'Beta-Alanine',
    tagline: 'One of the most solidly evidenced sports-nutrition compounds — muscle carnosine buffering',
    summary:
      'Beta-alanine reliably raises muscle carnosine, which buffers the acid that limits high-intensity exercise performance — dozens of RCTs confirm both the carnosine increase and the performance benefit in 1-4 minute high-intensity tasks. For longevity, the value is supporting the higher-intensity training that preserves muscle and fitness with age. Tier A; 3.2-6.4 g/day, split doses, 4-6 week minimum.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'stem'],
    compoundId: 'beta-alanine',
    outline: [
      'Overview: rate-limiting precursor for muscle carnosine',
      'Mechanism: H+ buffering during high-intensity exercise',
      'Evidence summary — carnosine elevation and performance RCTs',
      'Dosing: 3.2-6.4 g/day, split to minimize paresthesia',
      'Monitoring: high-intensity exercise performance',
      'Safety: the harmless paresthesia effect',
      'Personal results template',
    ],
    mdxSlug: 'beta-alanine',
  },
  {
    slug: 'hmb',
    category: 'compounds',
    title: 'HMB (Beta-Hydroxy Beta-Methylbutyrate)',
    tagline: 'An anti-catabolic muscle-support compound — strongest exactly where longevity needs it: older adults',
    summary:
      'HMB reduces muscle protein breakdown, with the clearest RCT evidence in older adults and bed-rest/illness-recovery populations — exactly the muscle-loss-risk contexts a longevity audience cares about most. Evidence in young, healthy, already-training adults is weaker; creatine has the stronger case there. Tier B; 3 g/day for at-risk populations.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['stem', 'proteostasis'],
    compoundId: 'hmb',
    outline: [
      'Overview: an anti-catabolic mechanism, distinct from synthesis-focused compounds',
      'Mechanism: ubiquitin-proteasome pathway modulation',
      'Evidence summary — older-adult/bed-rest RCTs vs healthy-trainee data',
      'Dosing: 3 g/day for at-risk populations',
      'Monitoring: lean mass and strength during at-risk periods',
      'Safety: excellent tolerability profile',
      'Personal results template',
    ],
    mdxSlug: 'hmb',
  },
  {
    slug: 'nattokinase',
    category: 'compounds',
    title: 'Nattokinase',
    tagline: 'Real fibrinolytic activity — and a bleeding-risk profile that demands physician coordination',
    summary:
      'Nattokinase demonstrates genuine fibrinolytic (clot-dissolving) activity and modest blood-pressure reduction in small human trials, but cardiovascular-event outcome evidence is preliminary. The same mechanism that makes it interesting creates real bleeding-risk interactions with anticoagulants, antiplatelet medication, and even other mild-antiplatelet supplements. Tier C; physician awareness is essential before combining with any blood-thinning therapy.',
    evidenceTier: 'C',
    relatedHallmarkIds: ['inflammation'],
    compoundId: 'nattokinase',
    outline: [
      'Overview: a fibrinolytic enzyme from fermented soybeans',
      'Mechanism: fibrin degradation, blood pressure',
      'Evidence summary — mechanistic confirmation vs preliminary outcome data',
      'Dosing: 100 mg (~2000 FU)/day',
      'Monitoring: blood pressure and bleeding/bruising',
      'Safety: the bleeding-risk interaction profile (critical)',
      'Personal results template',
    ],
    mdxSlug: 'nattokinase',
  },

  // ── Synergies ──────────────────────────────────────────────────────────────
  {
    slug: 'glynac-nrf2-triad',
    category: 'synergies',
    title: 'NRF2 Defense Triad',
    tagline: 'GlyNAC + Sulforaphane + R-ALA',
    summary:
      'The foundational TNiC NRF2 stack: glutathione substrate (GlyNAC), gene transcription (sulforaphane), and redox recycling (R-ALA) — three layers of antioxidant defense.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'mito', 'proteostasis', 'inflammation'],
    synergyCompoundIds: ['glynac', 'sulforaphane', 'rala'],
    outline: [
      'Rationale: substrate + signal + recycle',
      'Mechanistic synergy map',
      'Evidence per compound + combination logic',
      'AM choreography & spacing',
      'Biomarker targets (GSH, oxLDL)',
      'Contraindications',
    ],
    mdxSlug: 'glynac-nrf2-triad',
  },
  {
    slug: 'nmn-resveratrol-sirt1',
    category: 'synergies',
    title: 'SIRT1 Activation Pair',
    tagline: 'NMN + Trans-Resveratrol',
    summary:
      'NAD+ provides the fuel; resveratrol activates the enzyme. Combined SIRT1 signaling drives mitochondrial biogenesis, epigenetic stability, and senescence resistance.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'epigenetic', 'senescence', 'nutrient'],
    synergyCompoundIds: ['nmn', 'resveratrol'],
    outline: [
      'Rationale: cofactor + activator',
      'SIRT1 mechanism deep-dive',
      'Trial data & PK considerations',
      'AM NMN / PM resveratrol timing',
      'Monitoring: NAD+ index',
      'When to skip resveratrol',
    ],
    mdxSlug: 'nmn-resveratrol-sirt1',
  },
  {
    slug: 'nad-mito-stack',
    category: 'synergies',
    title: 'NAD+ Mitochondrial Stack',
    tagline: 'NMN + Ca-AKG + Resveratrol',
    summary:
      'Triple-axis mitochondrial support: NAD+ restoration (NMN), TCA cycle & epigenetic cofactor (Ca-AKG), and sirtuin-driven biogenesis (resveratrol). Highest hallmark coverage combo.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'epigenetic', 'stem', 'genomic'],
    synergyCompoundIds: ['nmn', 'cakg', 'resveratrol'],
    outline: [
      'Rationale: energy + epigenetics + biogenesis',
      'Hallmark coverage matrix',
      'Evidence per leg',
      'Full-day dosing schedule',
      'Biomarker panel (NAD+, AKG)',
      'Cost & simplicity tiers',
    ],
    mdxSlug: 'nad-mito-stack',
  },
  {
    slug: 'berberine-resveratrol-ampk-sirt1',
    category: 'synergies',
    title: 'AMPK/SIRT1 Crosstalk Pair',
    tagline: 'Berberine + Resveratrol',
    summary:
      'AMPK and SIRT1 run a bidirectional feedback loop — berberine activates AMPK, which raises the NAD+/NADH ratio SIRT1 needs, and resveratrol-activated SIRT1 deacetylates LKB1 to re-activate AMPK. Two entry points into the same loop.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'nutrient', 'inflammation', 'epigenetic'],
    synergyCompoundIds: ['berberine', 'resveratrol'],
    outline: [
      'Rationale: energy sensor + deacetylase activator',
      'AMPK ↔ SIRT1 feedback loop mechanism',
      'Evidence per leg + combination logic',
      'Meal-anchored AM / fat-paired PM timing',
      'Biomarker targets (glucose, HbA1c)',
      'Contraindications (CYP3A4, glucose-lowering drugs)',
    ],
    mdxSlug: 'berberine-resveratrol-ampk-sirt1',
  },
  {
    slug: 'coq10-rala-redox-recycling',
    category: 'synergies',
    title: 'Redox Recycling Pair',
    tagline: 'CoQ10 + R-ALA',
    summary:
      'CoQ10 is the primary fat-soluble antioxidant in cell membranes and the mitochondrial electron transport chain; R-ALA is amphipathic and regenerates spent antioxidants — including CoQ10 itself — across both fat and water compartments.',
    evidenceTier: 'B',
    relatedHallmarkIds: ['mito', 'inflammation', 'genomic'],
    synergyCompoundIds: ['coq10', 'rala'],
    outline: [
      'Rationale: lipid-phase defender + universal recycler',
      'Redox recycling mechanism map',
      'Evidence per leg + combination logic',
      'Fat-paired AM CoQ10 / flexible R-ALA timing',
      'Biomarker targets (hs-CRP, glucose)',
      'Contraindications (warfarin, glucose-lowering drugs)',
    ],
    mdxSlug: 'coq10-rala-redox-recycling',
  },

  // ── Lifestyle ──────────────────────────────────────────────────────────────
  {
    slug: 'exercise',
    category: 'lifestyle',
    title: 'Exercise',
    tagline: 'The intervention no compound can replace',
    summary:
      'Zone 2 aerobic base, resistance training, and VO2max work — mapped to mitochondrial biogenesis, senescence clearance, telomere maintenance, and nutrient sensing.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['mito', 'senescence', 'telomeres', 'nutrient', 'inflammation', 'stem'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — sedentary vs trained vs deload',
      'Zone 2 vs HIIT vs resistance pyramid',
      'Weekly protocol template',
      'Lab tie-ins (hs-CRP, NAD+ index)',
      'Wearable signals (Zone 2, RHR, HRV)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'exercise',
  },
  {
    slug: 'sleep',
    category: 'lifestyle',
    title: 'Sleep',
    tagline: 'When repair happens — glymphatic, DNA, hormonal',
    summary:
      '7–9 hours with adequate slow-wave and REM sleep drives DNA repair, glymphatic clearance, growth hormone release, and cortisol normalization. Non-negotiable longevity pillar.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'proteostasis', 'inflammation', 'telomeres', 'communication'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — debt vs OSA vs stack timing',
      'Sleep architecture & repair windows',
      'Protocol: timing, light, temperature',
      'Lab tie-ins (hs-CRP, 8-OHdG)',
      'Wearable metrics (deep sleep, wake SD)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'sleep',
  },
  {
    slug: 'nutrition',
    category: 'lifestyle',
    title: 'Nutrition',
    tagline: 'Methyl donors, protein thresholds, and nutrient sensing',
    summary:
      'Protein adequacy for glycine/NAC synthesis, methyl donor support (B12, folate, choline), time-restricted eating, and low-glycemic patterns that modulate mTOR/AMPK.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['nutrient', 'epigenetic', 'dysbiosis', 'inflammation', 'autophagy'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — TRE readiness vs methyl donors',
      'Macro framework (protein, fiber, polyphenols)',
      'Methyl donor checklist',
      'Lab tie-ins (hs-CRP, AKG)',
      'Wearable proxies (fiber, eating window)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'nutrition',
  },
  {
    slug: 'stress',
    category: 'lifestyle',
    title: 'Stress & Recovery',
    tagline: 'Cortisol, HPA axis, and inflammaging acceleration',
    summary:
      'Chronic stress accelerates telomere attrition, elevates hs-CRP, impairs sleep architecture, and diverts resources from repair to survival signaling.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['telomeres', 'inflammation', 'communication', 'genomic', 'senescence'],
    outline: [
      'Hallmark impact matrix (primary/secondary)',
      'Decision tree — acute stress vs HRV collapse',
      'HPA axis & cortisol curve',
      'HRV training & breathwork protocols',
      'Lab tie-ins (hs-CRP, GSH)',
      'Wearable signals (HRV, stress score)',
      'Stack prerequisite gate',
      'Personal tracking template',
    ],
    mdxSlug: 'stress',
  },

  // ── Guides ──────────────────────────────────────────────────────────────
  {
    slug: 'testing-and-monitoring',
    category: 'guides',
    title: 'Testing & Monitoring Guide',
    tagline: 'What to test, when, and how to interpret',
    summary:
      'Comprehensive lab panel roadmap tied to TNiC biomarkers, hallmark risks, retest cadence, trend interpretation, and stack-adjustment triggers.',
    evidenceTier: 'A',
    relatedHallmarkIds: ['genomic', 'mito', 'inflammation', 'epigenetic', 'proteostasis'],
    outline: [
      'Tier 1 baseline panel',
      'Tier 2 advanced panel',
      'Retest cadence & decision tree',
      'Interpretation playbook & compare block',
      'Stack-adjustment triggers + compare links',
      'Lab day checklist & CSV upload',
      'Hallmark → biomarker reference',
    ],
    mdxSlug: 'testing-and-monitoring',
  },
];

export function getModuleBySlug(category: LibraryModuleCategory, slug: string): LibraryModule | undefined {
  return libraryModules.find((m) => m.category === category && m.slug === slug);
}

export function getModulesByCategory(category: LibraryModuleCategory): LibraryModule[] {
  return libraryModules.filter((m) => m.category === category);
}

export function getAllModuleParams(): { slug: LibraryModuleCategory; moduleSlug: string }[] {
  return libraryModules.map((m) => ({ slug: m.category, moduleSlug: m.slug }));
}

export function getModulePath(module: LibraryModule): string {
  return `/library/${module.category}/${module.slug}`;
}