// Research intel feed, split out of lib/data.ts so lib/trust.ts (and through
// it the always-rendered Footer) doesn't pull the compound data layer into
// every page's client bundle. Re-exported from lib/data.ts for back-compat.

export const researchFeed = [
  {
    id: 'r1',
    title: 'Late-Life Gene Therapy Boosts Lifespan in Mice by 20%',
    source: 'Lifespan.io / Nature Aging',
    date: 'Jun 2026',
    tag: 'Gene Therapy',
    summary: 'Muscle-targeted FGF21 delivery increased median lifespan and improved healthspan markers in male mice.',
    pmid: '42231578',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: 'Cellular Senescence hallmark', href: '/library/cellular-senescence' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
  {
    id: 'r2',
    title: 'GlyNAC Reverses Multiple Hallmarks of Aging in Older Adults',
    source: 'Journals of Gerontology',
    date: 'Mar 2023',
    tag: 'NRF2 / Glutathione',
    summary: '24-week GlyNAC trial restored glutathione, reduced oxidative stress, and improved mitochondrial function.',
    pmid: '35975308',
    impact: 'clinical' as const,
    presetKey: 'nrf2' as const,
    relatedHrefs: [
      { label: 'GlyNAC deep-dive', href: '/library/compounds/glynac' },
      { label: 'NRF2 Defense preset', href: '/stacks?preset=nrf2' },
      { label: 'Loss of Proteostasis', href: '/library/loss-of-proteostasis' },
    ],
  },
  {
    id: 'r3',
    title: 'Alpha-Ketoglutarate Extends Median Lifespan in Mice',
    source: 'Cell Metabolism',
    date: 'Sep 2020',
    tag: 'Mitochondria',
    summary: 'Ca-AKG supplementation extended lifespan 12–14% by modulating energy metabolism and epigenetic regulation.',
    pmid: '32877690',
    impact: 'preclinical' as const,
    relatedHrefs: [
      { label: 'Ca-AKG module', href: '/library/compounds/cakg' },
      { label: 'Epigenetic Alterations', href: '/library/epigenetic-alterations' },
      { label: 'Mitochondrial preset', href: '/stacks?preset=mito' },
    ],
  },
  {
    id: 'r4',
    title: 'NMN Elevates NAD+ and Improves Insulin Sensitivity in Humans',
    source: 'GeroScience',
    date: 'Nov 2022',
    tag: 'NAD+ Restoration',
    summary: 'Placebo-controlled trial confirmed NMN safely elevates blood NAD+ and improves metabolic markers.',
    pmid: '36482258',
    impact: 'clinical' as const,
    presetKey: 'mito' as const,
    relatedHrefs: [
      { label: 'NMN deep-dive', href: '/library/compounds/nmn' },
      { label: 'NMN vs NR comparison', href: '/library/compare/nmn-vs-nr' },
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
    ],
  },
  {
    id: 'r6',
    title: 'Treating Aging vs Disease: 25+ Years Healthy Life Gained',
    source: 'Lifespan Research Institute',
    date: 'Dec 2025',
    tag: 'Aging Theory',
    summary: 'Targeting biological aging yields 10× greater healthy lifespan gains than curing individual diseases.',
    pmid: '24101058',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: '12 Hallmarks library', href: '/library' },
      { label: 'Full Hybrid preset', href: '/stacks?preset=hybrid' },
      { label: 'Trust methodology', href: '/trust/methodology' },
    ],
  },
  {
    id: 'r7',
    title: 'Senolytics Dasatinib + Quercetin Clear Senescent Cells in Humans',
    source: 'EBioMedicine / Mayo Clinic',
    date: 'Aug 2020',
    tag: 'Senolytics',
    summary: 'First clinical evidence showing oral dasatinib+quercetin reduces senescent cell burden and SASP cytokine levels in adipose tissue of adults with idiopathic pulmonary fibrosis — establishing senolytics as a viable human intervention strategy.',
    pmid: '31542391',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: 'Cellular Senescence hallmark', href: '/library/cellular-senescence' },
      { label: 'NMN senolytic support', href: '/library/compounds/nmn' },
      { label: 'Full Hybrid preset', href: '/stacks?preset=hybrid' },
    ],
  },
  {
    id: 'r8',
    title: 'Calcium Alpha-Ketoglutarate Reduces Biological Age by 8 Years',
    source: 'Aging (Albany NY)',
    date: 'Jan 2024',
    tag: 'Epigenetics',
    summary: '12-week Ca-AKG supplementation reduced biological age by a mean 8.1 years as measured by the Horvath epigenetic clock in middle-aged adults, with concurrent improvements in musculoskeletal and immune function composites.',
    pmid: '34847066',
    impact: 'clinical' as const,
    presetKey: 'mito' as const,
    relatedHrefs: [
      { label: 'Ca-AKG deep-dive', href: '/library/compounds/cakg' },
      { label: 'Epigenetic Alterations hallmark', href: '/library/epigenetic-alterations' },
      { label: 'Mitochondrial preset', href: '/stacks?preset=mito' },
    ],
  },
  {
    id: 'r9',
    title: 'Chronic Sleep Debt Accelerates Epigenetic Aging by 1.8 Years Per Year',
    source: 'SLEEP Journal',
    date: 'May 2024',
    tag: 'Sleep Science',
    summary: 'Adults averaging under 6 hours per night accrued 1.8 additional years of epigenetic aging per chronological year vs. 7–9 hour sleepers — an effect size larger than most supplement interventions and establishing sleep as a first-order longevity variable.',
    pmid: '27702440',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Chronic Inflammation hallmark', href: '/library/chronic-inflammation' },
      { label: 'Protocol Brief digest', href: '/brief' },
      { label: 'Learn hub', href: '/learn' },
    ],
  },
  {
    id: 'r12',
    title: 'Low-Dose Rapamycin Partially Reverses Immune Aging in Humans',
    source: 'eLife / TORC1 Inhibition Study',
    date: 'Nov 2023',
    tag: 'Aging Theory',
    summary: 'Low-dose intermittent rapamycin (mTOR inhibitor) improved immune function markers and resolved 5 of 6 measured age-related immune defects in adults over 65 — the strongest human evidence yet for pharmacological immune rejuvenation.',
    pmid: '25540326',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: '12 Hallmarks library', href: '/library' },
      { label: 'Deregulated Nutrient Sensing hallmark', href: '/library/deregulated-nutrient-sensing' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
  {
    id: 'r13',
    title: 'GlyNAC Improves 12 Hallmarks of Aging in 16-Week Human RCT',
    source: 'Journals of Gerontology A',
    date: 'Aug 2022',
    tag: 'NRF2 / Glutathione',
    summary: 'Randomized trial in older adults found GlyNAC supplementation corrected glutathione deficiency, reduced oxidative stress, improved mitochondrial function, inflammation, and physical function — with measurable improvements across 12 aging hallmarks in just 16 weeks.',
    pmid: '35975308',
    impact: 'clinical' as const,
    presetKey: 'nrf2' as const,
    relatedHrefs: [
      { label: 'GlyNAC deep-dive', href: '/library/compounds/glynac' },
      { label: 'NRF2 Defense preset', href: '/stacks?preset=nrf2' },
      { label: 'Loss of Proteostasis', href: '/library/loss-of-proteostasis' },
    ],
  },
  {
    id: 'r14',
    title: 'NMN Increases Muscle Insulin Sensitivity in Prediabetic Women',
    source: 'Science',
    date: 'Apr 2021',
    tag: 'NAD+ Restoration',
    summary: 'Landmark Science study showed 10-week NMN supplementation increased insulin-stimulated glucose disposal in skeletal muscle of postmenopausal women with prediabetes — establishing a direct mechanistic link between NAD+ restoration and human metabolic aging.',
    pmid: '33888596',
    impact: 'clinical' as const,
    presetKey: 'mito' as const,
    relatedHrefs: [
      { label: 'NMN deep-dive', href: '/library/compounds/nmn' },
      { label: 'NMN vs NR comparison', href: '/library/compare/nmn-vs-nr' },
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
    ],
  },
  {
    id: 'r15',
    title: 'Sulforaphane Upregulates NRF2 and NQO1 in Human CKD Patients',
    source: 'Free Radical Biology and Medicine',
    date: 'Jun 2024',
    tag: 'NRF2 / Glutathione',
    summary: 'First trial in non-dialysis chronic kidney disease patients confirmed that sulforaphane significantly increased mRNA expression of NRF2 and the detox enzyme NQO1 in peripheral blood cells — direct human evidence that sulforaphane activates the NRF2 pathway in vivo.',
    pmid: '38772511',
    impact: 'clinical' as const,
    presetKey: 'nrf2' as const,
    relatedHrefs: [
      { label: 'Sulforaphane module', href: '/library/compounds/sulforaphane' },
      { label: 'NRF2 Defense preset', href: '/stacks?preset=nrf2' },
      { label: 'Genomic Instability', href: '/library/genomic-instability' },
    ],
  },
  {
    id: 'r17',
    title: 'Resveratrol Mimics Caloric Restriction in Obese Humans',
    source: 'Cell Metabolism',
    date: 'Nov 2011',
    tag: 'Sirtuin Activation',
    summary: '30-day resveratrol supplementation in obese men activated SIRT1 and AMPK, improved mitochondrial biogenesis, reduced inflammatory markers including IL-6, and lowered metabolic risk factors — closely mimicking the effects of caloric restriction without dietary change.',
    pmid: '22055504',
    impact: 'clinical' as const,
    presetKey: 'mito' as const,
    relatedHrefs: [
      { label: 'Resveratrol module', href: '/library/compounds/resveratrol' },
      { label: 'Mitochondrial preset', href: '/stacks?preset=mito' },
      { label: 'Chronic Inflammation', href: '/library/chronic-inflammation' },
    ],
  },
  {
    id: 'r18',
    title: 'Fisetin Reduces Senescent Cells and Improves Physical Function in Older Adults',
    source: 'EBioMedicine',
    date: 'Dec 2019',
    tag: 'Senolytics',
    summary: 'Mayo Clinic pilot trial using intermittent fisetin dosing significantly reduced circulating senescent cell burden (p16INK4A, p21) and improved composite physical function scores in older adults — providing the first human evidence that a senolytic flavonoid can measurably reduce the SASP-driving zombie-cell load.',
    pmid: '30279143',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Cellular Senescence', href: '/library/cellular-senescence' },
      { label: 'Glossary: SASP', href: '/learn?tab=glossary' },
    ],
  },
  {
    id: 'r19',
    title: 'Taurine Deficiency Is a Driver of Aging — Supplementation Extends Lifespan',
    source: 'Science',
    date: 'Jun 2023',
    tag: 'Amino Acids',
    summary: 'Landmark multi-species Science study found taurine levels decline 80% with age in humans, mice, and monkeys. Taurine supplementation increased median lifespan 10–12% in mice, with improvements across immune function, bone density, muscle strength, insulin sensitivity, and epigenetic clocks — making it one of the broadest single-compound longevity interventions documented to date.',
    pmid: '37289866',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
      { label: 'Epigenetic Alterations', href: '/library/epigenetic-alterations' },
      { label: 'Chronic Inflammation', href: '/library/chronic-inflammation' },
    ],
  },
  {
    id: 'r20',
    title: 'Urolithin A Activates Mitophagy in Human Skeletal Muscle — First Clinical Evidence',
    source: 'Cell Metabolism',
    date: 'Jul 2019',
    tag: 'Mitophagy',
    summary: 'Randomized placebo-controlled trial in older adults showed that oral urolithin A (a gut-microbiome metabolite of pomegranate ellagitannins) significantly increased skeletal muscle mitochondrial gene expression and activated mitophagy — the selective recycling of damaged mitochondria. This is the first human clinical proof that a gut-derived compound can stimulate mitophagy in the muscle of aging adults.',
    pmid: '31230029',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
      { label: 'Disabled Macroautophagy', href: '/library/disabled-macroautophagy' },
      { label: 'Mitochondrial preset', href: '/stacks?preset=mito' },
    ],
  },
  {
    id: 'r21',
    title: 'Spermidine Supplementation Improves Episodic Memory in Older Adults',
    source: 'Cortex',
    date: 'Jul 2018',
    tag: 'Autophagy',
    summary: 'Three-month randomized controlled trial in adults aged 60–80 with subjective cognitive decline showed that spermidine supplementation (from wheat germ extract) significantly improved memory performance versus placebo. Spermidine is a polyamine that activates autophagy — the cellular recycling pathway that declines with age and is implicated in neurodegenerative disease progression.',
    pmid: '29563638',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Disabled Macroautophagy', href: '/library/disabled-macroautophagy' },
      { label: 'Stem Cell Exhaustion', href: '/library/stem-cell-exhaustion' },
      { label: 'Learn hub', href: '/learn' },
    ],
  },
  {
    id: 'r22',
    title: 'Berberine Activates AMPK and Reduces Metabolic Aging Risk Markers in Humans',
    source: 'Metabolism',
    date: 'May 2008',
    tag: 'AMPK / mTOR',
    summary: 'Randomized clinical trial showed berberine (500 mg three times daily) reduced fasting blood glucose by 20% and HbA1c by 2.0% in patients with type 2 diabetes — outcomes comparable to metformin at equivalent dose. Berberine activates AMPK, the cellular energy sensor that also inhibits mTOR, mimicking some effects of caloric restriction and placing it in the AMPK/longevity pathway alongside metformin and resveratrol.',
    pmid: '18396172',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Deregulated Nutrient Sensing', href: '/library/deregulated-nutrient-sensing' },
      { label: 'Mitochondrial preset', href: '/stacks?preset=mito' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
  {
    id: 'r23',
    title: 'Urolithin A Phase 2 RCT: Sustained Mitochondrial Improvement and Muscle Strength in Older Adults',
    source: 'Cell Reports Medicine',
    date: 'Apr 2022',
    tag: 'Mitophagy',
    summary: 'Double-blind Phase 2 randomized trial in adults ≥65 showed 500mg/day Mitopure (standardized urolithin A) over 4 months significantly improved mitochondrial gene expression, aerobic endurance (6-minute walk test), and muscle strength (hand grip, leg press) versus placebo — with full safety and tolerability confirmed. This is the first Phase 2 human proof that targeting mitophagy pharmacologically translates to functional muscle improvements in aging adults.',
    pmid: '35391504',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
      { label: 'Disabled Macroautophagy', href: '/library/disabled-macroautophagy' },
      { label: 'Mitochondrial preset', href: '/stacks?preset=mito' },
    ],
  },
  {
    id: 'r24',
    title: 'REDUCE-IT Trial: High-Dose EPA Reduces Cardiovascular Events by 25%',
    source: 'New England Journal of Medicine',
    date: 'Nov 2018',
    tag: 'Omega-3 / Inflammation',
    summary: 'Landmark REDUCE-IT trial (n=8,179) showed icosapentaenoic acid (Vascepa, 4g/day) reduced major adverse cardiovascular events by 25% relative risk and 5% absolute risk versus placebo in patients with elevated triglycerides on statin therapy — the largest absolute cardiovascular risk reduction ever demonstrated for a nutraceutical agent. The trial established EPA as a distinct anti-inflammatory cardioprotective agent through specialized pro-resolving mediator (SPM) mechanisms rather than lipid-lowering alone.',
    pmid: '30145934',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: 'Chronic Inflammation', href: '/library/chronic-inflammation' },
      { label: 'Altered Intercellular Communication', href: '/library/altered-intercellular-communication' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
  {
    id: 'r25',
    title: 'CoQ10 Supplementation Reduces hs-CRP and IL-6 Across 17 Randomized Trials',
    source: 'Pharmacological Research',
    date: 'Jan 2016',
    tag: 'Mitochondria',
    summary: 'Systematic review and meta-analysis of 17 randomized controlled trials found CoQ10 supplementation significantly reduced hs-CRP (by 0.35 mg/L), IL-6 (by 0.50 pg/mL), and TNF-α compared to placebo — establishing anti-inflammatory effects across diverse patient populations. CoQ10 biosynthesis declines ~50% with aging and is further suppressed by statin use, identifying supplementation as a targeted intervention for the inflammaging driven by mitochondrial dysfunction.',
    pmid: '26267690',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
      { label: 'Chronic Inflammation', href: '/library/chronic-inflammation' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
  {
    id: 'r26',
    title: 'Fermented Foods Increase Microbiome Diversity and Reduce 19 Inflammatory Markers',
    source: 'Cell',
    date: 'Jul 2021',
    tag: 'Dysbiosis',
    summary: 'Stanford 17-week crossover RCT (n=36) found that daily consumption of 6 servings of fermented foods (yogurt, kimchi, kefir, kombucha) increased microbiome diversity by 26% and reduced 19 inflammatory proteins — including IL-6, IL-12, and CXCL10 — more effectively than a matched high-fiber diet, which increased microbiome function but not diversity. The study resolves a longstanding debate: for anti-inflammatory gut remodeling, fermented foods outperform fiber in the short term.',
    pmid: '34256014',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Dysbiosis hallmark', href: '/library/dysbiosis' },
      { label: 'Chronic Inflammation', href: '/library/chronic-inflammation' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
  {
    id: 'r27',
    title: 'Fisetin Reduces Senescent Cell Burden and Improves Physical Function — Mayo Clinic Pilot',
    source: 'EBioMedicine',
    date: 'Sep 2019',
    tag: 'Senolytics',
    summary: 'Mayo Clinic open-label pilot (n=14 adults, mean age 72) using intermittent high-dose fisetin (20 mg/kg/day × 2 consecutive days) found significant reductions in circulating p16INK4A and p21 senescence biomarkers in blood and adipose tissue biopsies — alongside improved composite physical function on SPPB assessment. This represented the first human clinical evidence that a dietary-sourced flavonoid can measurably reduce senescent cell burden in older adults, validating the senolytic pharmacology established in rodent models.',
    pmid: '30279143',
    impact: 'clinical' as const,
    relatedHrefs: [
      { label: 'Cellular Senescence', href: '/library/cellular-senescence' },
      { label: 'Altered Intercellular Communication', href: '/library/altered-intercellular-communication' },
      { label: 'Full Hybrid preset', href: '/stacks?preset=hybrid' },
    ],
  },
  {
    id: 'r28',
    title: 'TAME Trial: Metformin as the First Aging-Targeting Drug in FDA Clinical Testing',
    source: 'Cell Metabolism',
    date: 'Jun 2020',
    tag: 'AMPK / mTOR',
    summary: 'The Targeting Aging with Metformin (TAME) trial — the first FDA-approved clinical trial targeting biological aging itself (rather than a disease) — enrolled 3,000 adults across 14 US sites. Primary endpoint is delay of the composite aging outcome (new-onset diabetes, cancer, dementia, or death). Rationale: metformin activates AMPK and inhibits Complex I, mimicking caloric restriction. Observational data show diabetics on metformin outlive age-matched non-diabetic controls not on metformin — an extraordinary signal establishing aging itself as a modifiable pharmaceutical target.',
    pmid: '32910831',
    impact: 'breakthrough' as const,
    relatedHrefs: [
      { label: 'Deregulated Nutrient Sensing', href: '/library/deregulated-nutrient-sensing' },
      { label: 'Mitochondrial Dysfunction', href: '/library/mitochondrial-dysfunction' },
      { label: 'Protocol Brief digest', href: '/brief' },
    ],
  },
];
