/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompoundEngineRouteImport } from './routes/compound-engine'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Elite8RouteImport } from './routes/elite-8'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HallmarksRouteImport } from './routes/hallmarks'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as NicoRouteImport } from './routes/nico'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PeptidesRouteImport } from './routes/peptides'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as SirtuinAtlasRouteImport } from './routes/sirtuin-atlas'
import { Route as StacksRouteImport } from './routes/stacks'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrustRouteImport } from './routes/trust'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompoundEngineRoute = CompoundEngineRouteImport.update({
  id: '/compound-engine',
  path: '/compound-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Elite8Route = Elite8RouteImport.update({
  id: '/elite-8',
  path: '/elite-8',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HallmarksRoute = HallmarksRouteImport.update({
  id: '/hallmarks',
  path: '/hallmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const NicoRoute = NicoRouteImport.update({
  id: '/nico',
  path: '/nico',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PeptidesRoute = PeptidesRouteImport.update({
  id: '/peptides',
  path: '/peptides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const SirtuinAtlasRoute = SirtuinAtlasRouteImport.update({
  id: '/sirtuin-atlas',
  path: '/sirtuin-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksRoute = StacksRouteImport.update({
  id: '/stacks',
  path: '/stacks',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compound-engine': typeof CompoundEngineRoute
  '/dashboard': typeof DashboardRoute
  '/elite-8': typeof Elite8Route
  '/faq': typeof FaqRoute
  '/hallmarks': typeof HallmarksRoute
  '/insights': typeof InsightsRoute
  '/labs': typeof LabsRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/nico': typeof NicoRoute
  '/partnerships': typeof PartnershipsRoute
  '/peptides': typeof PeptidesRoute
  '/products': typeof ProductsRoute
  '/protocols': typeof ProtocolsRoute
  '/sirtuin-atlas': typeof SirtuinAtlasRoute
  '/stacks': typeof StacksRoute
  '/tools': typeof ToolsRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compound-engine': typeof CompoundEngineRoute
  '/dashboard': typeof DashboardRoute
  '/elite-8': typeof Elite8Route
  '/faq': typeof FaqRoute
  '/hallmarks': typeof HallmarksRoute
  '/insights': typeof InsightsRoute
  '/labs': typeof LabsRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/nico': typeof NicoRoute
  '/partnerships': typeof PartnershipsRoute
  '/peptides': typeof PeptidesRoute
  '/products': typeof ProductsRoute
  '/protocols': typeof ProtocolsRoute
  '/sirtuin-atlas': typeof SirtuinAtlasRoute
  '/stacks': typeof StacksRoute
  '/tools': typeof ToolsRoute
  '/trust': typeof TrustRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/compound-engine': typeof CompoundEngineRoute
  '/dashboard': typeof DashboardRoute
  '/elite-8': typeof Elite8Route
  '/faq': typeof FaqRoute
  '/hallmarks': typeof HallmarksRoute
  '/insights': typeof InsightsRoute
  '/labs': typeof LabsRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/nico': typeof NicoRoute
  '/partnerships': typeof PartnershipsRoute
  '/peptides': typeof PeptidesRoute
  '/products': typeof ProductsRoute
  '/protocols': typeof ProtocolsRoute
  '/sirtuin-atlas': typeof SirtuinAtlasRoute
  '/stacks': typeof StacksRoute
  '/tools': typeof ToolsRoute
  '/trust': typeof TrustRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/compound-engine'
    | '/dashboard'
    | '/elite-8'
    | '/faq'
    | '/hallmarks'
    | '/insights'
    | '/labs'
    | '/learn'
    | '/library'
    | '/nico'
    | '/partnerships'
    | '/peptides'
    | '/products'
    | '/protocols'
    | '/sirtuin-atlas'
    | '/stacks'
    | '/tools'
    | '/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/compound-engine'
    | '/dashboard'
    | '/elite-8'
    | '/faq'
    | '/hallmarks'
    | '/insights'
    | '/labs'
    | '/learn'
    | '/library'
    | '/nico'
    | '/partnerships'
    | '/peptides'
    | '/products'
    | '/protocols'
    | '/sirtuin-atlas'
    | '/stacks'
    | '/tools'
    | '/trust'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/compound-engine'
    | '/dashboard'
    | '/elite-8'
    | '/faq'
    | '/hallmarks'
    | '/insights'
    | '/labs'
    | '/learn'
    | '/library'
    | '/nico'
    | '/partnerships'
    | '/peptides'
    | '/products'
    | '/protocols'
    | '/sirtuin-atlas'
    | '/stacks'
    | '/tools'
    | '/trust'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompoundEngineRoute: typeof CompoundEngineRoute
  DashboardRoute: typeof DashboardRoute
  Elite8Route: typeof Elite8Route
  FaqRoute: typeof FaqRoute
  HallmarksRoute: typeof HallmarksRoute
  InsightsRoute: typeof InsightsRoute
  LabsRoute: typeof LabsRoute
  LearnRoute: typeof LearnRoute
  LibraryRoute: typeof LibraryRoute
  NicoRoute: typeof NicoRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PeptidesRoute: typeof PeptidesRoute
  ProductsRoute: typeof ProductsRoute
  ProtocolsRoute: typeof ProtocolsRoute
  SirtuinAtlasRoute: typeof SirtuinAtlasRoute
  StacksRoute: typeof StacksRoute
  ToolsRoute: typeof ToolsRoute
  TrustRoute: typeof TrustRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compound-engine': {
      id: '/compound-engine'
      path: '/compound-engine'
      fullPath: '/compound-engine'
      preLoaderRoute: typeof CompoundEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elite-8': {
      id: '/elite-8'
      path: '/elite-8'
      fullPath: '/elite-8'
      preLoaderRoute: typeof Elite8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hallmarks': {
      id: '/hallmarks'
      path: '/hallmarks'
      fullPath: '/hallmarks'
      preLoaderRoute: typeof HallmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nico': {
      id: '/nico'
      path: '/nico'
      fullPath: '/nico'
      preLoaderRoute: typeof NicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peptides': {
      id: '/peptides'
      path: '/peptides'
      fullPath: '/peptides'
      preLoaderRoute: typeof PeptidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sirtuin-atlas': {
      id: '/sirtuin-atlas'
      path: '/sirtuin-atlas'
      fullPath: '/sirtuin-atlas'
      preLoaderRoute: typeof SirtuinAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks': {
      id: '/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof StacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompoundEngineRoute: CompoundEngineRoute,
  DashboardRoute: DashboardRoute,
  Elite8Route: Elite8Route,
  FaqRoute: FaqRoute,
  HallmarksRoute: HallmarksRoute,
  InsightsRoute: InsightsRoute,
  LabsRoute: LabsRoute,
  LearnRoute: LearnRoute,
  LibraryRoute: LibraryRoute,
  NicoRoute: NicoRoute,
  PartnershipsRoute: PartnershipsRoute,
  PeptidesRoute: PeptidesRoute,
  ProductsRoute: ProductsRoute,
  ProtocolsRoute: ProtocolsRoute,
  SirtuinAtlasRoute: SirtuinAtlasRoute,
  StacksRoute: StacksRoute,
  ToolsRoute: ToolsRoute,
  TrustRoute: TrustRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
